version: '3'
services:
  pyroscope:
    image: pyroscope/pyroscope
    command:
      - server
    ports:
      - "4040:4040"
  jaeger:
    image: jaegertracing/all-in-one:1.33
    ports:
      - "14250:14250"
      - "14268:14268"
      - "16686:16686"
