version: '3'
services:
  pyroscope:
    image: pyroscope/pyroscope
    command:
      - server
    ports:
      - "4040:4040"
    environment:
      - PYROSCOPE_CONFIG=/pyroscope.yaml
      - PYROSCOPE_LOG_LEVEL=debug
    volumes:
      - ./pyroscope.yaml:/pyroscope.yaml
  jaeger:
    image: jaegertracing/all-in-one:1.33
    ports:
      - '6831:6831/udp'
      - "14250:14250"
      - "14268:14268"
      - "16686:16686"
    environment:
      - JAEGER_ENDPOINT=jaeger:14268/api/traces
  jaeger-ui:
    build:
      context: ''
      dockerfile: jaeger-ui/Dockerfile
    ports:
      - '4000:3000'
